# Generated by Django 3.2.7 on 2021-09-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='categ',
            new_name='cart',
        ),
    ]
