# Generated by Django 3.2.7 on 2021-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_item_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
