# Generated by Django 3.2.7 on 2021-09-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_item_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user_id',
        ),
    ]
