# Generated by Django 3.2.7 on 2021-09-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
    ]
